idf_component_register(SRCS  "main.c"
        "ssr_control.c"
        "th_sensor.c"
        "wifi.c"
        "led.c"
        "i2c.c"
        "wg_obj.c"
        "eth_w5500.c"
        PRIV_REQUIRES
        "mbedtls"
        "nvs_flash"
        "esp_driver_i2c"
        "esp_driver_gpio"
        "driver"
        "esp_timer"
        "esp_eth"
        "esp_netif"
        "esp_wifi")
